### ISSUE TITLE
soc issues with Fronius/Solaranzeige

### ISSUE THREAD

**Issue by thedoctor586** [Deepintheeast/AWTRIX3-Connector#2]
Hej,

After setting config.ini to readout values for SOC in Solaranzeige for Fronius I get errors in social.py

App: soc
 {'soc_Akkustand_SOC': 88.2}
Traceback (most recent call last):
  File "/home/pi/scripts/AWTRIX3-Connector/./awtrix3connect.py", line 166, in <module>
    main()
  File "/home/pi/scripts/AWTRIX3-Connector/./awtrix3connect.py", line 152, in main
    auswertung(app, data, config)
  File "/home/pi/scripts/AWTRIX3-Connector/auswertung.py", line 28, in auswertung
    module.auswertung(app, data, config)
  File "/home/pi/scripts/AWTRIX3-Connector/Auswertungen/soc.py", line 11, in auswertung
    if int(float(data["soc_Akkuatand_SOC"])) == 0:
                 ~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'soc_Akkuatand_SOC'

**Comment by Deepintheeast** [comment]
you have an typo in "soc_Akkuatand_SOC". -->  soc_Akkustand_SOC

**Comment by thedoctor586** [comment]
embarrassing.....

you're right. issue fixed. thank you and nice tool
